openvpn_dir: "/etc/openvpn"
openvpn_server_dir: "{{ openvpn_dir }}/server"
openvpn_client_dir: "{{ openvpn_dir }}/client"
openvpn_server_key_dir: "{{ openvpn_server_dir }}/keys"
openvpn_server_tls_crypt_v2: "{{ openvpn_server_key_dir }}/tls-crypt-v2.key"
openvpn_server_crt: "{{ openvpn_server_dir }}/server.crt"
openvpn_server_key: "{{ openvpn_server_key_dir }}/server.key"
openvpn_client_fingerprint_path_format: "{{ openvpn_client_dir }}/%s-fp.txt"
openvpn_server_fingerprint: "{{ openvpn_server_dir }}/fingerprint.txt"

masquerade_ipv4_network_tcp: "10.8.0.0"
masquerade_ipv4_network_udp: "10.8.1.0"
masquerade_ipv4_netmask: "255.255.255.0"
masquerade_ipv4_prefix: "24"
