- name: restart systemd openvpn
  loop:
    - server-tcp
    - server-udp
  loop_control:
    loop_var: conf_name
  ansible.builtin.systemd_service:
    name: "openvpn-server@{{ conf_name }}"
    state: restarted

- name: reload openvpn
  ansible.builtin.service:
    name: openvpn
    state: reloaded
