name: check unsuitable commit of files
on:
  pull_request:
    paths:
      - config.yml
      - '**/dev/**'
  push:
    paths:
      - config.yml
      - '**/dev/**'

jobs:
  fail:
    if: ${{ github.event.repository.is_template }}
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    steps:
      - run: false
